<?php

namespace StevenBuehner\BibleVerseBundle\Repository;

/**
 * BibleVerseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibleVerseRepository extends \Doctrine\ORM\EntityRepository {
}
